apiVersion: v1
kind: PersistentVolume
metadata:
  name: dshuttle-pv
  labels:
    name: dshuttle-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: alluxio
    volumeHandle: alluxio
    volumeAttributes:
      alluxio.master.hostname: "dshuttle-master.default"
