apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dshuttle-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["dshuttle-pv"]
